variables:
- &platforms linux/amd64,linux/arm64,linux/riscv64
- &image woodpeckerci/plugin-docker-buildx
- &kine_tag 'v0.11.9'
- &maintainers 'Mateusz Urbanek <mateusz.urbanek.98@gmail.com>'
- logins: &logins
  - registry: https://ghcr.io/
    username: shanduur-auto
    password:
      from_secret: ghcr-token
- &backend_options
  kubernetes:
    securityContext:
      privileged: true

when:
- event: push
  branch: main
- event: manual

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  kine:
    image: *image
    privileged: true
    settings:
      dockerfile: ./containers/kine/Dockerfile
      context: ./containers/kine
      registry: ghcr.io
      repo: ghcr.io/anza-labs/kine
      logins:
      - <<: *logins
      platforms: *platforms
      tags: *kine_tag
      build_args_from_env:
      - MAINTAINERS
      - VERSION
    environment:
      MAINTAINERS: *maintainers
      VERSION: *kine_tag
    backend_options:
      <<: *backend_options
    when:
    - path:
        include:
        - '.woodpecker/kine.yaml'
        - 'containers/kine/*'
