variables:
- &platforms linux/riscv64
- &image woodpeckerci/plugin-docker-buildx
- &mars_cm_sd_linux_branch 'dev-mars-cm-sdcard'
- &maintainers 'Mateusz Urbanek <mateusz.urbanek.98@gmail.com>'
- logins: &logins
  - registry: https://ghcr.io/
    username: shanduur-auto
    password:
      from_secret: ghcr-token
- &backend_options
  kubernetes:
    securityContext:
      privileged: true

when:
- event: push
  branch: main
- event: manual

steps:
  mars_cm_sd_linux:
    image: *image
    privileged: true
    settings:
      dockerfile: ./linux/mars_cm_sd4/Dockerfile
      context: ./linux/mars_cm_sd4
      registry: ghcr.io
      repo: ghcr.io/anza-labs/linux
      logins:
      - <<: *logins
      platforms: *platforms
      tags: *mars_cm_sd_linux_branch
      build_args_from_env:
      - MAINTAINERS
      - BRANCH
    environment:
      BRANCH: *mars_cm_sd_linux_branch
      MAINTAINERS: *maintainers
    backend_options:
      <<: *backend_options
    when:
    - path:
        include:
        - '.woodpecker/linux-rpi4.yaml'
        - 'linux/mars_cm_sd4/*'
