variables:
- &platforms linux/riscv64
- &image woodpeckerci/plugin-docker-buildx
- &mars_cm_sd_linux_branch 'dev-mars-cm-sdcard'
- &maintainers 'Mateusz Urbanek <mateusz.urbanek.98@gmail.com>'
- logins: &logins
  - registry: https://ghcr.io/
    username: shanduur-auto
    password:
      from_secret: ghcr-token
- &backend_options
  kubernetes:
    securityContext:
      privileged: true

when:
- event: push
  branch: main
- event: manual

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: false

steps:
  submodule:
    image: woodpeckerci/plugin-git
    commands:
    - git submodule update --init --depth=1 linux/milkv-mars-cm-sdcard/src

  mars_cm_sd_linux:
    image: *image
    privileged: true
    settings:
      dockerfile: ./linux/milkv-mars-cm-sdcard/Dockerfile
      context: ./linux/milkv-mars-cm-sdcard
      registry: ghcr.io
      repo: ghcr.io/anza-labs/linux
      logins:
      - <<: *logins
      platforms: *platforms
      tags: *mars_cm_sd_linux_branch
      build_args_from_env:
      - MAINTAINERS
      - BRANCH
    environment:
      BRANCH: *mars_cm_sd_linux_branch
      MAINTAINERS: *maintainers
    backend_options:
      <<: *backend_options
    when:
    - path:
        include:
        - '.woodpecker/linux-mars-cm-sd.yaml'
        - 'linux/milkv-mars-cm-sdcard/*'
