variables:
- &platforms linux/arm64
- &image woodpeckerci/plugin-docker-buildx
- &raspberrypi_linux_branch 'rpi-6.6.y'
- &maintainers 'Mateusz Urbanek <mateusz.urbanek.98@gmail.com>'
- logins: &logins
  - registry: https://ghcr.io/
    username: shanduur-auto
    password:
      from_secret: ghcr-token
- &backend_options
  kubernetes:
    securityContext:
      privileged: true

when:
- event: push
  branch: main
- event: manual

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: false

steps:
  submodule:
    image: woodpeckerci/plugin-git
    commands:
    - git submodule update --init --depth=1 linux/raspberrypi-cm4/src

  raspberrypi_linux:
    image: *image
    privileged: true
    settings:
      dockerfile: ./linux/raspberrypi-cm4/Dockerfile
      context: ./linux/raspberrypi-cm4
      registry: ghcr.io
      repo: ghcr.io/anza-labs/linux
      logins:
      - <<: *logins
      platforms: *platforms
      tags: *raspberrypi_linux_branch
      build_args_from_env:
      - MAINTAINERS
      - BRANCH
    environment:
      BRANCH: *raspberrypi_linux_branch
      MAINTAINERS: *maintainers
    backend_options:
      <<: *backend_options
    when:
    - path:
        include:
        - '.woodpecker/linux-rpi-cm4.yaml'
        - 'linux/raspberrypi-cm4/*'
